"""
Willow Skill: Post Status Report
Generate a flight report as an MDX file in the Starlight docs
"""

from typing import Optional, Dict, Any
from neo4j import GraphDatabase
import os
import certifi
from datetime import datetime
import json

NEO4J_URI = os.getenv("NEO4J_URI")
NEO4J_USER = os.getenv("NEO4J_USER")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD")

def execute(report_title: str, report_data: Optional[Dict[str, Any]] = None, auto_query: bool = True) -> dict:
    """
    Generate a flight report MDX file in the Starlight docs

    Args:
        report_title: Title of the flight report
        report_data: Optional dict with custom report data. If None and auto_query=True, queries AuraDB
        auto_query: If True, automatically queries infrastructure and task status

    Returns:
        dict with file path and generation status
    """
    os.environ['SSL_CERT_FILE'] = certifi.where()
    os.environ['REQUESTS_CA_BUNDLE'] = certifi.where()

    timestamp = datetime.now()
    date_str = timestamp.strftime("%Y-%m-%d")
    time_str = timestamp.strftime("%H:%M:%S")
    filename = timestamp.strftime("%Y-%m-%d-%H%M%S")

    # Auto-query AuraDB if requested
    if auto_query and report_data is None:
        report_data = _query_system_status()
    elif report_data is None:
        report_data = {}

    # Generate MDX content
    mdx_content = f"""---
title: Flight Report - {report_title}
description: System status report generated on {date_str} at {time_str}
---

# 📊 Flight Report: {report_title}

**Generated**: {date_str} at {time_str}
**Type**: Automated System Report

---

## Executive Summary

{report_data.get('summary', 'Status report generated by Willow system.')}

---

## Infrastructure Status

"""

    # Add infrastructure data
    if 'infrastructure' in report_data:
        for node in report_data['infrastructure'].get('nodes', []):
            status_class = 'status-active' if node.get('status') == 'Active' else 'status-pending'
            mdx_content += f"""
### {node.get('name', 'Unknown')}
- **Role**: {node.get('role', 'N/A')}
- **Status**: <span class="status-badge {status_class}">{node.get('status', 'Unknown')}</span>
- **Address**: `{node.get('address', 'N/A')}`
- **Services**: {', '.join(node.get('services', [])) if node.get('services') else 'None'}
"""

    mdx_content += "\n---\n\n## Task Status\n\n"

    # Add task data
    if 'tasks' in report_data:
        tasks_by_status = {}
        for task in report_data['tasks']:
            status = task.get('status', 'Unknown')
            if status not in tasks_by_status:
                tasks_by_status[status] = []
            tasks_by_status[status].append(task)

        for status, tasks in tasks_by_status.items():
            status_icon = {
                'Complete': '✅',
                'In Progress': '🟡',
                'Not Started': '⚪',
                'Blocked': '🔴'
            }.get(status, '❓')

            mdx_content += f"\n### {status_icon} {status} ({len(tasks)})\n\n"
            for task in tasks:
                mdx_content += f"- **{task.get('name', 'Unknown')}**"
                if task.get('assignee'):
                    mdx_content += f" (Assigned: {task['assignee']})"
                if task.get('blockers'):
                    mdx_content += f"\n  - ⚠️ Blocked by: {', '.join(task['blockers'])}"
                mdx_content += "\n"

    mdx_content += "\n---\n\n## Recent Activity\n\n"

    # Add recent diary entries
    if 'diary_entries' in report_data:
        mdx_content += "<div class=\"flight-report\">\n\n"
        for entry in report_data['diary_entries'][:10]:  # Last 10 entries
            mdx_content += f"""
**{entry.get('agent', 'Unknown')}** - {entry.get('timestamp', 'Unknown')}
Task: _{entry.get('task', 'N/A')}_
> {entry.get('notes', 'No notes')}

"""
        mdx_content += "</div>\n"

    # Add custom sections
    if 'custom_sections' in report_data:
        for section in report_data['custom_sections']:
            mdx_content += f"\n---\n\n## {section.get('title', 'Custom Section')}\n\n"
            mdx_content += f"{section.get('content', '')}\n"

    mdx_content += f"""
---

## Metadata

- **Report Type**: {report_data.get('type', 'General Status')}
- **Generated By**: Willow System (core/skills/post_status.py)
- **Timestamp**: {timestamp.isoformat()}
- **Data Sources**: AuraDB, Infrastructure Health Checks

---

**Next Review**: {report_data.get('next_review', 'TBD')}
"""

    # Write to file
    docs_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
        'domains', 'docs', 'src', 'content', 'docs', 'reports'
    )

    os.makedirs(docs_path, exist_ok=True)
    file_path = os.path.join(docs_path, f"{filename}.mdx")

    try:
        with open(file_path, 'w') as f:
            f.write(mdx_content)

        return {
            "success": True,
            "file_path": file_path,
            "filename": f"{filename}.mdx",
            "timestamp": timestamp.isoformat(),
            "url": f"/reports/{filename}/"
        }
    except Exception as e:
        return {
            "success": False,
            "error": str(e)
        }


def _query_system_status() -> Dict[str, Any]:
    """
    Query AuraDB for current system status

    Returns:
        dict with infrastructure, tasks, and diary entries
    """
    driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASSWORD))

    try:
        with driver.session() as session:
            # Query infrastructure
            infra_result = session.run("""
                MATCH (i:Infrastructure)
                OPTIONAL MATCH (i)-[:HOSTS]->(s)
                RETURN i.name as name,
                       i.role as role,
                       i.status as status,
                       i.network_address as address,
                       collect(s.name) as services
            """)

            infrastructure = {
                "nodes": [
                    {
                        "name": record["name"],
                        "role": record["role"],
                        "status": record["status"],
                        "address": record["address"],
                        "services": record["services"]
                    }
                    for record in infra_result
                ]
            }

            # Query tasks
            tasks_result = session.run("""
                MATCH (t:Task)
                OPTIONAL MATCH (t)-[:DEPENDS_ON]->(dep:Task)
                RETURN t.name as name,
                       t.status as status,
                       t.assignee as assignee,
                       collect(dep.name) as blockers
                ORDER BY t.status DESC
                LIMIT 50
            """)

            tasks = [
                {
                    "name": record["name"],
                    "status": record["status"],
                    "assignee": record["assignee"],
                    "blockers": [b for b in record["blockers"] if b]
                }
                for record in tasks_result
            ]

            # Query recent diary entries
            diary_result = session.run("""
                MATCH (t:Task)-[:HAS_DIARY_ENTRY]->(d:DiaryEntry)
                RETURN d.agent as agent,
                       d.timestamp as timestamp,
                       d.notes as notes,
                       t.name as task
                ORDER BY d.timestamp DESC
                LIMIT 20
            """)

            diary_entries = [
                {
                    "agent": record["agent"],
                    "timestamp": str(record["timestamp"]),
                    "notes": record["notes"],
                    "task": record["task"]
                }
                for record in diary_result
            ]

            # Generate summary
            total_tasks = len(tasks)
            completed = len([t for t in tasks if t['status'] == 'Complete'])
            in_progress = len([t for t in tasks if t['status'] == 'In Progress'])

            summary = f"""
The Willow system is operational with {len(infrastructure['nodes'])} active infrastructure nodes.

**Task Overview**:
- Total Tasks: {total_tasks}
- Completed: {completed} ({int(completed/total_tasks*100) if total_tasks > 0 else 0}%)
- In Progress: {in_progress}
- Recent Activity: {len(diary_entries)} diary entries in the last period
"""

            return {
                "summary": summary.strip(),
                "infrastructure": infrastructure,
                "tasks": tasks,
                "diary_entries": diary_entries,
                "type": "Automated System Status",
                "next_review": "Next agent session"
            }

    except Exception as e:
        return {
            "summary": f"Error querying system: {str(e)}",
            "infrastructure": {"nodes": []},
            "tasks": [],
            "diary_entries": []
        }
    finally:
        driver.close()


if __name__ == "__main__":
    # Test execution
    result = execute("Daily System Status", auto_query=True)
    print(json.dumps(result, indent=2))
