"""
Sync Memory (Backup) Skill
==========================

Backs up Willow's "Memory" and internal state from AuraDB to a local Neo4j instance.
Excludes sensitive business data (Policy, Claim, Customer, etc.).
Generates an `env.offline` configuration for fallback usage.

Usage:
    python core/skills/sync_memory.py
"""

import os
import sys
from neo4j import GraphDatabase
from typing import List, Set
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

from core.clients.graph_client import GraphClient

# Configuration
# Source will be handled by GraphClient (env auto-loaded from .env)
# Target: Local Neo4j Container (from docker-compose)
TARGET_URI = os.getenv("BACKUP_NEO4J_URI", "bolt://localhost:7687")
TARGET_USER = os.getenv("BACKUP_NEO4J_USER", "neo4j")
TARGET_PASSWORD = os.getenv("BACKUP_NEO4J_PASSWORD", "willow_backup")

# Definition of "Willow" vs "Business"
INCLUDE_LABELS = {
    "Agent", "Memory", "Conversation", "Turn", "Task", "Skill", 
    "Concept", "RFC", "DiaryEntry", "Component", "Domain", 
    "Project", "User", "Artifact", "Document", "Message"
}

EXCLUDE_LABELS = {
    "Policy", "Claim", "Quote", "Risk", "Vehicle", 
    "Customer", "Person", "Pet", "Payment", "BankDetails"
}

def get_target_driver():
    try:
        return GraphDatabase.driver(TARGET_URI, auth=(TARGET_USER, TARGET_PASSWORD))
    except Exception as e:
        print(f"❌ Failed to connect to Target {TARGET_URI}: {e}")
        return None

def sync_nodes(graph_client, target_tx):
    print("⏳ Fetching Nodes from AuraDB via Gateway...")
    labels_condition = " OR ".join([f"n:{label}" for label in INCLUDE_LABELS])
    exclude_condition = " AND ".join([f"NOT n:{label}" for label in EXCLUDE_LABELS])
    
    query = f"""
    MATCH (n)
    WHERE ({labels_condition}) AND ({exclude_condition})
    RETURN labels(n) as labels, properties(n) as props, elementId(n) as source_id
    """
    
    records = graph_client.run(query)
    count = 0
    
    for record in records:
        labels = record["labels"]
        props = record["props"]
        source_id = record["source_id"]
        valid_labels = [l for l in labels if l not in EXCLUDE_LABELS]
        if not valid_labels: continue
            
        labels_str = ":".join(valid_labels)
        cleaned_props = {k: v for k, v in props.items() if v is not None}
        cleaned_props["_backup_id"] = source_id 
        
        target_tx.run(f"CREATE (n:{labels_str}) SET n = $props", props=cleaned_props)
        count += 1
        
    print(f"✅ Synced {count} nodes.")
    return count

def sync_relationships(graph_client, target_tx):
    print("⏳ Fetching Relationships from AuraDB via Gateway...")
    
    labels_condition_start = " OR ".join([f"a:{label}" for label in INCLUDE_LABELS])
    exclude_condition_start = " AND ".join([f"NOT a:{label}" for label in EXCLUDE_LABELS])
    labels_condition_end = " OR ".join([f"b:{label}" for label in INCLUDE_LABELS])
    exclude_condition_end = " AND ".join([f"NOT b:{label}" for label in EXCLUDE_LABELS])

    query = f"""
    MATCH (a)-[r]->(b)
    WHERE ({labels_condition_start}) AND ({exclude_condition_start})
      AND ({labels_condition_end}) AND ({exclude_condition_end})
    RETURN elementId(a) as start_id, elementId(b) as end_id, type(r) as r_type, properties(r) as r_props
    """
    
    records = graph_client.run(query)
    count = 0
    
    for record in records:
        start_id = record["start_id"]
        end_id = record["end_id"]
        r_type = record["r_type"]
        r_props = record["r_props"]
        cleaned_props = {k: v for k, v in r_props.items() if v is not None}
        
        target_tx.run(f"""
        MATCH (a), (b)
        WHERE a._backup_id = $start_id AND b._backup_id = $end_id
        CREATE (a)-[r:{r_type}]->(b)
        SET r = $props
        """, start_id=start_id, end_id=end_id, props=cleaned_props)
        count += 1

    print(f"✅ Synced {count} relationships.")
    return count

def clear_target(target_tx):
    print("🧹 Clearing Target Database...")
    target_tx.run("MATCH (n) DETACH DELETE n")
    print("✅ Target Database Cleared.")

def generate_offline_env():
    print("📝 Generating env.offline...")
    content = f"""# Willow Offline Configuration
# Generated by sync_memory.py
NEO4J_URI={TARGET_URI}
NEO4J_USER={TARGET_USER}
NEO4J_PASSWORD={TARGET_PASSWORD}
LLM_PROVIDER=ollama
OLLAME_BASE_URL=http://localhost:11434
"""
    with open("env.offline", "w") as f:
        f.write(content)
    print("✅ Created env.offline")

def main():
    print("🧠 Willow Memory Sync: AuraDB -> Local Backup")
    
    # Target driver
    target_driver = get_target_driver()
    if not target_driver:
        return

    # Source client (AuraDB via Gateway)
    # The client automatically uses WILLOW_GATEWAY_URL from env or defaults to bunny:8001
    graph_client = GraphClient(agent_id="Memory_Backup_Agent")

    try:
        # Verify source access
        graph_client.run("RETURN 1")
        print("✅ Connected to AuraDB via Gateway.")
        
        with target_driver.session() as target_session:
            target_session.execute_write(clear_target)
            
            # Perform Sync
            target_session.execute_write(lambda t_tx: sync_nodes(graph_client, t_tx))
            target_session.execute_write(lambda t_tx: sync_relationships(graph_client, t_tx))

        generate_offline_env()
        print("🚀 Backup Complete.")
        
    except Exception as e:
        print(f"❌ Critical Error during Sync: {e}")
    finally:
        target_driver.close()

if __name__ == "__main__":
    main()
